Models/Entities/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace inSpark.Models.Entities
{
    public class Job
    {

        [Key]
        [Required]
        [Display(Name = "Job ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Job Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Application DeadLine")]
        public DateTime DeadLine { get; set; }

        [Required]
        [Display(Name ="Date Published")]
        public DateTime DatePublished { get; set; }
        public int NoOfApplicants { get; set; }

        [Required]
        public string JobRequirementPath { get; set; }


        [Required]
        [Display(Name ="Mail Salutation (E.g Dear, Hi, Hello)")]
        public string MailSalutation { get; set; }

        [Required]
        [Display(Name ="Rejection Mail Message.")]
        public string RejectionMailMessage { get; set; }

        [Required]
        [Display(Name = "Acceptance Mail Message.")]
        public string AcceptanceMailMessage { get; set; }
    }
}

Models/ViewModels/JobViewModels.cs
using inSpark.Infrastructure.Services;
using inSpark.Models.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace inSpark.Models.ViewModels
{
  

    public class ReApplyViewModel
    {
        public string ApplicantName { get; set; }
        public Guid JobId { get; set; }
        public string JobTitle { get; set; }
        public string ApplicantId { get; set; }
    }


    public class JobFormViewModel
    {

        [Display(Name = "Job ID")]
        public Guid Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Job Title")]
        public string Title { get; set; }

        [Required]
        [MustBeFutureDate]
        [Display(Name = "Application DeadLine (mm/dd/yyyy)")]
        public DateTime DeadLine { get; set; }

        //[Required]
        public HttpPostedFileBase JobRequirement { get; set; }

        [Required]
        [Display(Name = "Mail Salutation (E.g Dear, Hi, Hello)")]
        public string MailSalutation { get; set; }

        [Required]
        [Display(Name = "Rejection Mail Message.")]
        public string RejectionMailMessage { get; set; }

        [Required]
        [Display(Name = "Acceptance Mail Message.")]
        public string AcceptanceMailMessage { get; set; }
    }

    public class JobApplicationStatusViewModel
    {
        public string JobTitle { get; set; }
        public string ApplicantName { get; set; }
        public JobApplicationStatus JobApplicationStatus { get; set; }
            
    }
}

Controllers/JobsController.cs
using inSpark.Infrastructure.Interfaces;
using inSpark.Infrastructure.Services;
using inSpark.Models.Entities;
using inSpark.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using inSpark.Models;
using System.Threading.Tasks;
using AutoMapper;

namespace inSpark.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        public IJobDbService _jobDbContext;
        public IApplicantDbService _applicationDbContext;
        public JobsController(IJobDbService jobContext,IApplicantDbService applicationContext)
        {
            _jobDbContext = jobContext;
            _applicationDbContext = applicationContext;
        }


        // GET: Jobs
        [AllowAnonymous]
        public ActionResult Index()
        {
            var jobs = _jobDbContext.GetActiveJobs();
         
            return View("JobListReadOnly", jobs);
        }

        public async Task<ActionResult> Apply(Guid jobId)
        {
            if (User.IsInRole(UserRoles.CanApplyForJobs))
            {
                var userId = User.Identity.GetUserId();
                Job job = _jobDbContext.ReadItem(jobId);

                //save job application to applications table
                JobApplicationStatus isApplicationSuccessful = _applicationDbContext.SaveJobApplication(userId, job);
                
                if (isApplicationSuccessful == JobApplicationStatus.Successuful)
                {
                    //update no of applicants in jobs table
                    _jobDbContext.UpdateNoOfApplicantsCount(jobId);

                    //Notify Admin of application
                    
                    ApplicationUser applicant = _applicationDbContext.GetApplicantDetails(userId);
                    await MailService.NotifyAdminOfApplicantion(applicant.FullName, job.Title);
                }
                    
                if (isApplicationSuccessful == JobApplicationStatus.AlreadyApplied)
                {

                    return View("ReApply", new ReApplyViewModel()
                    {
                        ApplicantName = _jobDbContext.GetUserFullName(userId),
                        JobId = jobId,
                        JobTitle=job.Title,
                        ApplicantId = User.Identity.GetUserId()
                    }
                    );
                }
                //Display Application status View
                var viewModel=new JobApplicationStatusViewModel()
                {
                    ApplicantName = User.Identity.Name,
                    JobTitle = _jobDbContext.ReadItem(jobId).Title,
                    JobApplicationStatus = isApplicationSuccessful,
                };
                return View("ApplicationStatus", viewModel);

            }
            else
                return RedirectToAction("Login", "Account", new { message = "Please Login as Applicant to continue." });
   
            
        }

        public ActionResult UpdateApplication(string applicantId)
        {

            ApplicationUser applicantDetails=_applicationDbContext.GetApplicantDetails(applicantId);
            UpdateApplicantDetailsViewModel model;
            model = Mapper.Map<ApplicationUser, UpdateApplicantDetailsViewModel>(applicantDetails);
            return RedirectToAction("UpdateUser","Account",model);

        }
    }
}

Views/Jobs/ApplicationStatus.cshtml
@model inSpark.Models.ViewModels.JobApplicationStatusViewModel
@{
    ViewBag.Title = "ApplicaionStatus";
    string message;
    if (@Model.JobApplicationStatus == inSpark.Infrastructure.Services.JobApplicationStatus.ApplicationClosed)
    {
        message = "Your Application for the " + Model.JobTitle +" position was not successful because Application has being closed";
    }
    else if(@Model.JobApplicationStatus == inSpark.Infrastructure.Services.JobApplicationStatus.Successuful)
    {
        message = "Your Application for" + Model.JobTitle + " was  successful.";
    }
    else
    {
        message = "An Error occured during Your Application for the " + Model.JobTitle + " position";
    }

}

<div table-fullpage div-padded-50px>
    <p text-center text-primary >
        Hi @Model.ApplicantName, <br /> 
        @message;
    </p>
</div>

Views/Jobs/JobListReadOnly.cshtml
@model IEnumerable<inSpark.Models.Entities.Job>
@{
    ViewBag.Title = "Careers";
}


<div class="banner-section">
    <img id="banner-img" src="~/Content/images/careerbanner.jpg" alt="backgroiund image">
    <h1>See how far your thinking can go</h1>
</div>
<div class="mid-section">
    <div class="growth-card">
        <h1>Endless growth opportunities</h1>
        <p>
            Our firms culture is rooted in our core
            principles. Here, you will join diverse and
            inclusive teams that support each other and
            empower you to do your best work.
        </p>
    </div>
    <img id="img-glasgow" src="~/Content/images/people-Glasgow.jpg" alt="">
</div>


<h1 class="jobs-header">Open Positions</h1>
<div id="open-positions">
    @if (Model != null)
    {
        foreach (inSpark.Models.Entities.Job job in Model)
        {
            if (job.DeadLine - DateTime.Now.AddDays( 1) > new TimeSpan())
            {
                <div id = "job-card" >
                    <h3>@job.Title</h3>
                    <p>Application Deadline: @job.DeadLine.ToString("d")</p>
                    <div class="job-card-footer">
                        <a id="job-requirement" href="@job.JobRequirementPath" target="_blank">
                            <i class="fas fa-download"> Job Requirements</i>
                            
                        </a>
                        <div class="apply">
                             @Html.ActionLink("Apply Now", "Apply", "Jobs", null, null, null, new { jobId = job.Id }, new {@style= "color:#337ab7; font-weight:600" })
                           
                        </div>
                    </div>
                </div>
            }
            
        }
    }
    else
    {
        <h1>No Open Positions For now</h1>
        <a>Join our mailing list</a>
    }



</div>

Views/Jobs/ReApply.cshtml
@model inSpark.Models.ViewModels.ReApplyViewModel
@{
    ViewBag.Title = "ReApply";
}

<h4>Hi @Model.ApplicantName, <br />
    You already applied for the @Model.JobTitle Job, <br> Do you Want to Update your Application Details?</h4>
<div>
    @Html.ActionLink("Yes","UpdateApplication","Jobs", new {applicantId=Model.ApplicantId },null)
    @Html.ActionLink("No","Index","Home")
</div>